Declare 
	@w_return             int,
	@t_corr               char(1),
	@t_ssn_corr           int,
    @i_cliente			  int,
	@i_producto           smallint,
	@i_cta_banco          cuenta,
	@i_val                money,	
	@i_banco              char(4),
	@i_referencia         int,
	@i_concepto           descripcion,
	@i_tran_servicio      char(1) ,
	@i_trace			  varchar(64),
	@i_op_code            varchar(8),
	@i_cta_orig           varchar(20),
	@i_tipo_ced_org	      char(1),
	@i_cedula_org	      numero,
	@i_telefono_org	      varchar(12),
	@i_tipo_ced_dest      char(1),
	@i_cedula_dest	      numero,
	@i_telefono_dest	  varchar(12),	
	@i_nom_cliente_benef  varchar(64),
	@o_sec                int,
    @o_resultado		  VARCHAR(3),
	@o_cod_error		  INT,
	@o_mensaje            varchar(64)  

SET @i_referencia         = CAST((900000000 * RAND()) + 100000000 AS NUMERIC(9,0))
SELECT 
	@t_corr               = 'N',
	@t_ssn_corr           = null, --116398904,
    @i_cliente			  = 148431,
	@i_producto           = 3,
	@i_cta_banco          = '01690009531001365052',
	@i_val                =  CAST(RAND() * 10.0 AS MONEY),	
	@i_banco              = '0114',
	@i_concepto           = 'descripcion',
	@i_tran_servicio      = 'N',
	@i_trace			  = '0200' + convert(varchar(10), @i_referencia),
	@i_op_code            = '560000',
	@i_cta_orig           = '01051234432112345321',
	@i_tipo_ced_org	      = 'V',
	@i_cedula_org	      = '14300380',
	@i_telefono_org	      = '584123296222',
	@i_tipo_ced_dest      = 'J',
    @i_cedula_dest        = '296886679',
    @i_telefono_dest      = '584122713237', --'04129196677',  
    @i_nom_cliente_benef  = 'SURNET'

exec @w_return = cob_cuentas..sp_atm_pago_socio_ws
    @s_user               = 'EntradaR4',
    @t_corr               = @t_corr,
	@t_ssn_corr           = @t_ssn_corr,
	@i_cliente			  = @i_cliente,
	@i_producto           = @i_producto,
	@i_cta_banco          = @i_cta_banco,
	@i_val                = @i_val,	
	@i_banco              = @i_banco,
	@i_referencia         = @i_referencia,
	@i_concepto           = @i_concepto,
	@i_tran_servicio      = @i_tran_servicio,
	@i_trace			  = @i_trace,
	@i_op_code            = @i_op_code,
	@i_cta_orig           = @i_cta_orig,
	@i_tipo_ced_org	      = @i_tipo_ced_org,
	@i_cedula_org	      = @i_cedula_org,
	@i_telefono_org	      = @i_telefono_org,
	@i_tipo_ced_dest      = @i_tipo_ced_dest,
	@i_cedula_dest	      = @i_cedula_dest,
	@i_telefono_dest	  = @i_telefono_dest,	
	@i_nom_cliente_benef  = @i_nom_cliente_benef,
	@o_sec                = @o_sec out,
    @o_resultado		  = @o_resultado OUT,
	@o_cod_error		  = @o_cod_error OUT,
	@o_mensaje			  = @o_mensaje OUT

SELECT @w_return, @o_sec, @o_resultado, @o_cod_error, @o_mensaje